### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by Tevin-yue** [sn-lab/MouseGoggles#20]
Hi, it is a wonderful project and thanks for your sharing. I met some problems with installing when I followed this project. I have tried the version of raspberry with legacy, 32 bit or 64 bit, but the Godot engine can not open correctly. I wanna to know which version of raspberry and godotengine are compatible to run the  project. Also ,the circular display are not sold anymore, so I have to change the display that satisfy the driver.

**Comment by misaacson01** [comment]
Hello Tevin

flatpak install flathub org.godotengine.Godot3

**Comment by Tevin-yue** [comment]
Hello, I have tried your solution, it seems that I still got something wrong. The error infromation is attached.

As for display, I am still looking for the proper one.

![error1](https://github.com/sn-lab/MouseGoggles/assets/80507794/19a41172-1d85-453f-9ad5-93098142cc0e)
![error2](https://github.com/sn-lab/MouseGoggles/assets/80507794/b931bf57-bc7b-4a78-a034-b1617c9f4252)

**Comment by Tevin-yue** [comment]
Now, I have added an HDMI screen and it is working. However, it seems that the VNC view from SSH has a problem. I have encountered other problems as well:

1. Once I install the driver, Godot can no longer open.

2. I've noticed that the reset and cs pin settings in the config.h file are different from the defined pins used on the Raspberry Pi, according to the PowerPoint file in the hardware.

It would be kind of you to provide some suggestions. Thanks a lot.

**Comment by misaacson01** [comment]
I am not sure about the VNC question, I personally haven't used it with this system. Probably best to first get it working without VNC.

1. After installing and starting the driver, I assume you're opening up a new command window to run Godot? What happens exactly when you try to run Godot? If you can, let me know of any error messages you see, and also the details of your system and installation (whether you're installing ili9341 or st7789; which Raspberry Pi board you're using and where you bought it; what OS version you've installed; which Godot version you've installed).

2. [This graphic](https://www.etechnophiles.com/wp-content/uploads/2020/12/R-Pi-3-B-Pinout.jpg) should explain the differences, the Raspberry Pi has a specific pin naming system but it should all be connected correctly in the PCB and named correctly in the software.

**Comment by misaacson01** [comment]
@Tevin-yue This may have been from a comment that was deleted because the issue has been resolved, but I noticed a new display that appears to be this waveshare display: https://www.waveshare.com/product/1.28inch-lcd-module.htm
In the case that you're trying out this display, I just wanted to let you know that I'm also testing this display (which uses a new GC9A01 chip) and recently wrote a new driver that works for it, so let me know if you'd like it!

**Comment by monrky** [comment]
hi matthew! i am also experiencing a similar godot installation issue - i had to reset our raspberry pi for other reasons (i believe we are still using duo 1.0? or whatever the first version is).  

```
vrpi@raspberrypi:~ $ flatpak install flathub org.godotengine.Godot
Looking for matches…
error: Nothing matches org.godotengine.Godot in remote flathub
vrpi@raspberrypi:~ $ flatpak install flathub org.godotengine.Godot3

Looking for matches…
error: Nothing matches org.godotengine.Godot3 in remote flathub


```

i've also tried downloading it online directly from flathub, but i'm unsure what to do with the file once downloaded 

any help you can offer would be very appreciated!! thanks for all your help :)

**Comment by misaacson01** [comment]
Hi @monrky!

I think there have been some changes to the flathub Godot, on the whole it's a little unstable. I've more recently switched to a different host/version of Godot, which has been working great and doesn't require flatpak at all. Downloading and running it is a little different, but it's very simple. This is what it being used for all our latest headsets. Here is the instructions for installing and running this version of Godot: (taken from EyeTrack v.1.1 installation instructions)

**Install the Godot game engine**

- Start the Raspberry Pi and connect to the internet.
- Open up the github page for the [Unofficial Godot Engine for the Raspberry Pi](https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi/tree/main?tab=readme-ov-file#compiling).
- In the "Downloads" section, download the zip file for 3.5.2 - Raspberry Pi 4
- After the zip file has been downloaded, navigate to your "downloads" folder, right-click on the zip file, and click "extract here"
- Inside the unzipped folder, find the "...editor_Ito.bin" file. This is the executable file for running the godot game engine. To run the engine, double-click this file and select "Execute".


After you install this version of Godot, if you are using Duo 1.0, you'll still have to use the earlier Godot projects as the newer ones (e.g. Godot project 2.0, used by EyeTrack 1.1) are made for newer displays. But I'm sure you've made changes to the Godot project you were using before and are planning to copy that to the new system.

Let me know how this goes!

**Comment by monrky** [comment]
Works great! thanks!!
